name: Rust - Test & Publish Package

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
#    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build and Test
        working-directory: toolchain
        run: |
          cargo build --package chidori-core --package chidori-im-hashmap --package chidori-prompt-format --package chidori-static-analysis
          cargo test --package chidori-core --package chidori-im-hashmap --package chidori-prompt-format --package chidori-static-analysis
      - name: Publish chidori-prompt-format
        working-directory: toolchain/chidori-prompt-format
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish chidori-static-analysis
        working-directory: toolchain/chidori-static-analysis
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish chidori-core
        working-directory: toolchain/chidori-core
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
